spring:
  datasource:
    tomcat:
      init-s-q-l: SET NAMES utf8mb4
# MySQL连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauthserver?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ENC(YiYjVwTulDGN//YaB3KbuA==) #明文root，可以直接用username: root
    password: 123456 #明文19941017，可以直接用password: 19941017
    druid:
      validation-query: SELECT 1
      connection-init-sqls: SET NAMES utf8mb4
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect

#pagehelper分页插件
pagehelper:
    #禁用reasonable分页参数合理化，页码小于1或者大于最大页码返回空数据
    reasonable: false
    params: count=countSql
    # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012
    helper-dialect: mysql
    support-methods-arguments: true