-- 2019-05-11 by simon 修改T_USERS表的sex列为boolean
ALTER TABLE T_USERS ADD SEX_TEMP CHAR (1) CHECK (SEX_TEMP IN(0, 1));
UPDATE T_USERS SET SEX_TEMP = SEX;
ALTER TABLE T_USERS MODIFY SEX NULL;
UPDATE T_USERS SET SEX = NULL;
ALTER TABLE T_USERS MODIFY (SEX CHAR (1) CHECK (SEX IN(0, 1)));
UPDATE T_USERS SET SEX = SEX_TEMP;
UPDATE T_USERS SET SEX = '1' WHERE SEX IS NULL;
ALTER TABLE T_USERS MODIFY SEX NOT NULL;
ALTER TABLE T_USERS DROP COLUMN SEX_TEMP;

-- 2019-05-11 by simon 修改T_USERS表的enabled列为boolean
ALTER TABLE T_USERS ADD ENABLED_TEMP CHAR (1) CHECK (ENABLED_TEMP IN(0, 1));
UPDATE T_USERS SET ENABLED_TEMP = ENABLED;
ALTER TABLE T_USERS MODIFY ENABLED NULL;
UPDATE T_USERS SET ENABLED = NULL;
ALTER TABLE T_USERS MODIFY (ENABLED CHAR (1) CHECK (ENABLED IN(0, 1)));
UPDATE T_USERS SET ENABLED = ENABLED_TEMP;
UPDATE T_USERS SET ENABLED = '1' WHERE enabled IS NULL;
ALTER TABLE T_USERS MODIFY ENABLED NOT NULL;
ALTER TABLE T_USERS DROP COLUMN ENABLED_TEMP;

-- 2019-05-11 by simon 修改T_S_COLUMN_UI表的id列为long类型
ALTER TABLE T_S_COLUMN_UI MODIFY (ID NUMBER(20));