-- 2019-05-11 by simon 修改T_USERS表的sex列为boolean
ALTER TABLE T_USERS ADD SEX_TEMP CHAR (1) CHECK (SEX_TEMP IN(0, 1));
UPDATE T_USERS SET SEX_TEMP = SEX;
ALTER TABLE T_USERS MODIFY SEX NULL;
UPDATE T_USERS SET SEX = NULL;
ALTER TABLE T_USERS MODIFY (SEX CHAR (1) CHECK (SEX IN(0, 1)));
UPDATE T_USERS SET SEX = SEX_TEMP;
UPDATE T_USERS SET SEX = '1' WHERE SEX IS NULL;
ALTER TABLE T_USERS MODIFY SEX NOT NULL;
ALTER TABLE T_USERS DROP COLUMN SEX_TEMP;

-- 2019-05-11 by simon 修改T_USERS表的enabled列为boolean
ALTER TABLE T_USERS ADD ENABLED_TEMP CHAR (1) CHECK (ENABLED_TEMP IN(0, 1));
UPDATE T_USERS SET ENABLED_TEMP = ENABLED;
ALTER TABLE T_USERS MODIFY ENABLED NULL;
UPDATE T_USERS SET ENABLED = NULL;
ALTER TABLE T_USERS MODIFY (ENABLED CHAR (1) CHECK (ENABLED IN(0, 1)));
UPDATE T_USERS SET ENABLED = ENABLED_TEMP;
UPDATE T_USERS SET ENABLED = '1' WHERE enabled IS NULL;
ALTER TABLE T_USERS MODIFY ENABLED NOT NULL;
ALTER TABLE T_USERS DROP COLUMN ENABLED_TEMP;

-- 2019-05-11 by simon 修改T_S_COLUMN_UI表的id列为long类型
ALTER TABLE T_S_COLUMN_UI MODIFY (ID NUMBER(20));

-- 2019-05-14 by simon 修改T_BILL的BILL_CONTEXT列为varchar(255)类型
ALTER TABLE T_BILL DROP COLUMN BILL_CONTEXT;
ALTER TABLE T_BILL ADD (BILL_CONTEXT NVARCHAR2(255));

-- 2019-05-15 by simon 给所有表添加缺失的主键和唯一键
ALTER TABLE T_BILL ADD PRIMARY KEY (ID);
ALTER TABLE T_DICT_TYPE ADD PRIMARY KEY (ID);
ALTER TABLE T_AUTHORITIES ADD PRIMARY KEY (ID);
ALTER TABLE T_DICT_TYPE_GROUP ADD PRIMARY KEY (ID);
ALTER TABLE T_LOG_LOGIN ADD PRIMARY KEY (ID);
ALTER TABLE T_MULTI_LANGUAGE ADD PRIMARY KEY (ID);
ALTER TABLE T_NEWS_INFO ADD PRIMARY KEY (ID);
ALTER TABLE T_NEWS_TAG ADD PRIMARY KEY (ID);
ALTER TABLE T_NOTICE_MSG ADD PRIMARY KEY (ID);
ALTER TABLE T_QR_CODE ADD PRIMARY KEY (ID);
ALTER TABLE T_RESET_PWD_INFO ADD PRIMARY KEY (ID);
ALTER TABLE T_S_CITY ADD PRIMARY KEY (ID);
ALTER TABLE T_S_COLUMN_UI ADD PRIMARY KEY (ID);
ALTER TABLE T_S_COUNTRY ADD PRIMARY KEY (ID);
ALTER TABLE T_S_FONT_AWESOME ADD PRIMARY KEY (ID);
ALTER TABLE T_S_PROVINCE ADD PRIMARY KEY (ID);
ALTER TABLE T_S_QUARTZ_JOB ADD PRIMARY KEY (ID);
ALTER TABLE T_S_TOWN ADD PRIMARY KEY (ID);
ALTER TABLE T_S_VILLAGE ADD PRIMARY KEY (ID);
ALTER TABLE T_SIDE_MENU ADD PRIMARY KEY (ID);
ALTER TABLE T_SIDE_MENU_AUTHORITY ADD PRIMARY KEY (ID);
ALTER TABLE T_USERS ADD PRIMARY KEY (ID);
ALTER TABLE T_VERI_CODE ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX ix_auth_username ON T_AUTHORITIES (user_id ASC, authority ASC);

-- 2019-05-21 by simon 修改数据
update t_side_menu set url='/api/loggingEvents/list' where id=93126997827387392;

-- 2019-05-23 by simon 删除t_veri_code表
drop table t_veri_code;